--ARREGLOS ASOCIATIVOS Y DEMAS FUNCIONES DE ELLOS
DECLARE
 TYPE ARREGLO IS TABLE OF VARCHAR(100) INDEX BY PLS_INTEGER;
 DATOS ARREGLO;
BEGIN
  DATOS(1):='ELEMENTO 1';
  DATOS(2):='ELEMENTO 2';
  DATOS(3):='ELEMENTO 3';
  DATOS(4):='ELEMENTO 4';
  DATOS(5):='ELEMENTO 5';
  DATOS(6):='ELEMENTO 6';
  --FUNCION COUNT, CUENTA CUANTO DATOS HAY EN UN TABLA
  FOR ITERACION IN 1..DATOS.COUNT LOOP
  DBMS_OUTPUT.PUT_LINE(DATOS(ITERACION));
  END LOOP;
  
  --FUNCION PRIOR RETORNAR EL INDICE ANTES DEL INDICE QUE LE INDICAMOS COMO PARAMETRO
  DBMS_OUTPUT.PUT_LINE(DATOS.PRIOR(3));
  --FUNCION NEXT RETORNA EL INDICE ANTES DEL INDICE QUE LE INDICAMOS COMO PARAMETRO
  DBMS_OUTPUT.PUT_LINE(DATOS.next(3));
  --ELIMINA EL REGISTRO CORESPONDIENTE AL INDICE QUE LE INQUEMOS COMO PARAMETRO
  datos.delete(1);
  
  dbms_output.put_line('LA CANTIDAD DE VALORES ES: ' || datos.count);
  --SEGUNDA MANERA DE HACER USO DEL DELETE. AQUI ELIMINAR LOS ELEMENTOS ENTRE EL INDICE 2 Y 4
    datos.delete(2,4);
  
  dbms_output.put_line('LA CANTIDAD DE VALORES ES: ' || datos.count);
END;