--AQUI ESTAMOS INDICANDOLE QUE NOS CONVIERTA UN CAMPO A FORMATO FECHA Y EN EL SEGUNDO PARAMETRO TENEMOS QUE INDICAR EL ORDEN DE COMO ESTA EN EL PRIMER CAMPO
SELECT ORDER_DATE, TO_CHAR(TO_DATE(ORDER_DATE,'YYYYMMDD'),'YYYY-MM-DD') ,TO_TIMESTAMP(ORDER_DATE,'YYYYMMDD HH:MI:SS') FROM ORDERS;
--OJO LA FUNCION TO_CHAR RECIBE COMO PARAMETRO LO QUE RETORNA LA FUNCION ORDER_DATE COMO PRIMER PARAMETRO.

--COMO OBTENER UNA SUBCADENA APARTIR DE UNA CADENA
--LA FUNCION SUBSTR RECIBE COMO PARAMETRO PRIMERO: LA FUENTE DEL STRING, SEGUNDO DESDE DONDE VA A TOMAR, TERCERO HASTA DONDE VA A FINAL EL SUBSTRING
SELECT CATEGORY_NAME ,SUBSTR(CATEGORY_NAME,1,5) FROM CATEGORIES;
