DECLARE
NOMBRE PRODUCTS.PRODUCT_NAME%TYPE;
FECHA DATE;
CODIGO_ERROR NUMBER;
MENSAJE_ERROR VARCHAR2(1000);

BEGIN
  FECHA:=SYSDATE;
  SELECT PRODUCT_NAME INTO NOMBRE FROM PRODUCTS WHERE PRODUCT_ID=545445; -- AQUI ESTAMOS PONIENDO UN ID QUE NO EXISTE PARA PRODUCIR UN ERROR
  DBMS_OUTPUT.PUT_LINE('eL NOMBRE DEL PRODUCTO CON ID 1 ES: '||NOMBRE);
  
  EXCEPTION 
    WHEN TOO_MANY_ROWS THEN
      CODIGO_ERROR:=SQLCODE;
      MENSAJE_ERROR:=SQLERRM;
    --LA VARIABLE SQLCODE NOS GUARDA EL CODIGO DE DICHO ERROR QUE ESTAMOS CAPTURANDO
      DBMS_OUTPUT.PUT_LINE('SE RETORNARON MUCHOS REGISTROS EN LA SENTENCIA SELECT INTO. EL CODIGO DEL ERROR ES: '|| CODIGO_ERROR );
      --PARA MOSTRAS EL MENSAJE DEL ERROR IMPRIMIR LA VARIABLE SQLERRM
      DBMS_OUTPUT.PUT_LINE(MENSAJE_ERROR);
      --USAMOS EL OTHERS CUANDO NO SABEMOS QUE EXCEPCION ES LA NOS SALTA Y ASI PODEMOS SABER QUE CODIGO DE ERROR ES
    WHEN OTHERS THEN
    CODIGO_ERROR:=SQLCODE;
      IF(CODIGO_ERROR=-1858) THEN
        MENSAJE_ERROR:=SQLERRM;
        DBMS_OUTPUT.PUT_LINE('SE ESTA ASIGNANDO TIPOS DE DATOS IMCOMPATIBLES');
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL ERROR ES: '|| CODIGO_ERROR );
        DBMS_OUTPUT.PUT_LINE(MENSAJE_ERROR);
      END IF;
    --CODIGO CUANDO EL SELECT INTO NO ENCUENTRA DATOS  
    IF (CODIGO_ERROR=100) THEN
      MENSAJE_ERROR:=SQLERRM;
      DBMS_OUTPUT.PUT_LINE('EL SELECT INTO NO ENCONTRO DATOS');
      DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL ERROR ES: '|| CODIGO_ERROR );
      DBMS_OUTPUT.PUT_LINE(MENSAJE_ERROR);
    END IF;
END;

SET SERVEROUTPUT ON;