--creacion de usuarios
create user BD_BICIBLETAS  IDENTIFIED by 0101
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;
--creacion de roles
CREATE ROLE ADMINISTRADORES;
--asignacion de provilegios
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE,DROP ANY TABLE,DROP ANY PROCEDURE TO ADMINISTRADORES;
--asignar roles a un asuario
GRANT ADMINISTRADORES TO BD_BICIBLETAS;

--CONSULTAR LOS ROLES
select * from DBA_ROLES;

--CONSULTAS PARA VERIFICAR PRIVILEGIOS A UN ROL
select * from DBA_SYS_PRIVS where GRANTEE='ADMINISTRADORES';