--ESTRUCTURA PARA CREACION DE UNA SECUENCIA
CREATE SEQUENCE SQ_TABLA_CATEGORIAS
START WITH 5
INCREMENT BY 1;
--FUNCION NEXTVAL LO QUE HACE ES SUMAR 1 A EL VALOR ACTUAL DE LA FRECUENCIA
INSERT INTO CATEGORIES VALUES(SQ_TABLA_CATEGORIAS.NEXTVAL,'MINI BICICLETAS');

DECLARE
  VALOR_ACTUAL_SQ NUMBER;
  
BEGIN
--FUNCION CURRVAL LO QUE HACE ES OBTENER EL VALOR ACTUAL EN QUE SE ENCUENTRA LA SECUENCIA
  VALOR_ACTUAL_SQ:=SQ_TABLA_CATEGORIAS.CURRVAL;
  DBMS_OUTPUT.PUT_LINE('EL VALOR ACTUAL DE LA SECUENCIA ES: '|| VALOR_ACTUAL_SQ);
  COMMIT;

END;

SET SERVEROUTPUT ON;