CREATE TABLE BITACORA(
  PK_COD_BITACORA NUMBER PRIMARY KEY,
  DESCRIPCION VARCHAR2(2000),
  FECHA_HORA TIMESTAMP,
  USUARIO VARCHAR2(100),
  OPERACION VARCHAR2 (50)
);

CREATE SEQUENCE SQ_BITACORA
START WITH 1
INCREMENT BY 1;

-----trigger--------
CREATE OR REPLACE TRIGGER TG_COUNTRIES
AFTER INSERT OR UPDATE OR DELETE ON COUNTRIES
FOR EACH ROW
BEGIN 
  IF (INSERTING) THEN
  INSERT INTO BITACORA VALUES (SQ_BITACORA.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA COUNTRIES 
  Y EL DATO NUEVO EN EL ID ES: '||:NEW.COUNTRY_ID||' Y EL NOMBRE DEL NUEVO PAIS ES: ' ||:NEW.COUNTRY_NAME,
  SYSTIMESTAMP, USER, 'INSERT');
  END IF;
  IF(UPDATING) THEN
  INSERT INTO BITACORA VALUES (SQ_BITACORA.NEXTVAL, 'SE REALIZO UN UPDATE EN LA TABLA COUNTRIES 
  EL NOMBRE DEL NUEVO PAIS ES: ' ||:NEW.COUNTRY_NAME || 'Y EL NOMBRE DEL PAIS ANTERIOR ES: '|| :OLD.COUNTRY_NAME,
  SYSTIMESTAMP, USER, 'UPDATE');
  END IF;
  IF(DELETING) THEN
    INSERT INTO BITACORA VALUES (SQ_BITACORA.NEXTVAL, 'SE REALIZO UN DELETE EN LA TABLA COUNTRIES 
    Y EL DATO ELIMINADO EN EL ID ES: '||:OLD.COUNTRY_ID||' Y EL NOMBRE DEL PAIS ERA: ' ||:OLD.COUNTRY_NAME,
    SYSTIMESTAMP, USER, 'DELETE');
  END IF;
  
END;

--PROBANDO TRIGGER PARA INSERT
  BEGIN
    INSERT INTO COUNTRIES  VALUES ('HN','HONDURAS',1);
    COMMIT;
  END;
--PROBANDO TRIGGER PARA UPDATE
  BEGIN
    UPDATE COUNTRIES SET REGION_ID=2 WHERE COUNTRY_ID='HN';
    COMMIT;
  END;
--PROBANDO TRIGGER PARA DELETE
  BEGIN
    DELETE COUNTRIES WHERE COUNTRY_ID='HN';
    COMMIT;
  END;
  
  SELECT * FROM COUNTRIES;
    
  SELECT * FROM BITACORA;