--OBTENIENDO EL ULTIMO ID DE 
SELECT EMPLOYEE_ID FROM EMPLOYEES ORDER BY ROWNUM DESC;

--CREANDO LA SECUENCIA
CREATE SEQUENCE SQ_TABLA_EMPLEADOS
START WITH 108
INCREMENT BY 1;

--CREACION BLOQUE ANONIMO
DECLARE
  CODIGO_ERROR NUMBER;
  MENSAJE_ERROR VARCHAR2(1000);
BEGIN
  INSERT INTO EMPLOYEES VALUES (SQ_TABLA_EMPLEADOS.NEXTVAL,'GUSTAVO','GAMERO','TAVOGAMERO@GMAIL.COM',3394838,to_date('15-DEC-16','DD-MON-RR'),15,'Programmer');
  INSERT INTO EMPLOYEES VALUES (SQ_TABLA_EMPLEADOS.NEXTVAL,'EDUARDO','ROMERO','EDUARDOROMERO@GMAIL.COM',4654645,to_date('23-JUL-15','DD-MON-RR'),14,'Marketing Representative');
  INSERT INTO EMPLOYEES VALUES (SQ_TABLA_EMPLEADOS.NEXTVAL,'MANUEL','MARTINEZ','MANUELMARTINES1234@GMAIL.COM',6756756,to_date('20-NOV-12','DD-MON-RR'),13,'Sales Manager');
  INSERT INTO EMPLOYEES VALUES (SQ_TABLA_EMPLEADOS.NEXTVAL,'JUAN','HERNANDEZ','JUANROBANDO@GMAIL.COM',34234234,to_date('25-JUN-10','DD-MON-RR'),12,'Administration Vice President');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('REGISTROS ALMACENADOS');
  EXCEPTION
  WHEN OTHERS THEN
    CODIGO_ERROR:=SQLCODE;
    MENSAJE_ERROR:=SQLERRM;
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('SE HA PRODUCIDO UN ERROR CON CODIGO: '||CODIGO_ERROR);
    DBMS_OUTPUT.PUT_LINE(MENSAJE_ERROR);
END;