
  --FUNCIONES DE CAMBIO DE FORMATO Y DEMAS RELACIONES CON HORA Y FECHA ADEMAS DE COMO CONVERTIR A DISTINTOS FORMATOS.

  DECLARE
  FECHA DATE; --ALMACENA FECHA SOLO
  FECHA_HORA TIMESTAMP; --ALMACENA FECHA Y HORA
  

BEGIN
  FECHA:= SYSDATE;
  DBMS_OUTPUT.PUT_LINE('LA FECHA OBTENIDA CON SYSDATE ES: '|| FECHA);
  
  FECHA_HORA:=SYSTIMESTAMP;
  DBMS_OUTPUT.PUT_LINE('LA FECHA Y HORA OBTENIDA CON SYSTIMESTAMP ES: '|| FECHA_HORA);
  
  --RECIBE 2 PARAMETROS EL PRIMER VALOR INDICA LA FECHA Y LUEGO EL FORMATO EN LA QUE FECHA ES ENTREGADA
  FECHA:= TO_DATE('2020-01-27','yyyy-mm-dd');
  DBMS_OUTPUT.PUT_LINE('LA FECHA OBTENIDA CON TO_DATE ES: '|| FECHA);
  
  --LO MISMO QUE LA ANTERIOR PERO ESTA RECIBE 2 PARAMETROS Y LUEGO EL FORMATO EN LA QUE EL FORMATO ES MOSTRADO 
  FECHA_HORA:=TO_TIMESTAMP('25-02-2022 11:30:16','DD-MM-YYYY HH:MI:SS');
  DBMS_OUTPUT.PUT_LINE('LA FECHA Y HORA OBTENIDA CON TOTIMESTAMP ES: '|| FECHA_HORA);
  
  --RECIBE COMO PARAMETRO UNA VARIABLE CON UNA FECHA Y TAMBIEN EL FORMATO AL CUAL ESTA SE DESEA REALIZAR EL CAMBIO
  DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE LA FECHA: '|| TO_CHAR(FECHA,'DD-MM-YYYY'));
  
  DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE LA FECHA Y HORA: '|| TO_CHAR(FECHA_HORA,'DD-MM-YYYY HH-MI-SS'));
  
  --PARA MOSTRAR LA HORA EN FORMATO DE 24 HORAS
  FECHA_HORA:=TO_TIMESTAMP('25-02-2022 23:30:16','DD-MM-YYYY HH24:MI:SS');
  DBMS_OUTPUT.PUT_LINE('LA FECHA Y HORA OBTENIDA CON TOTIMESTAMP ES: '|| FECHA_HORA);
  
  DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE LA FECHA Y HORA: '|| TO_CHAR(FECHA_HORA,'DD-MM-YYYY HH-MI-SS AM'));
  

  --FUNCION USER
  --COMO MIRAR CON QUE USUARIO ESTAMOS CONECTADOS
  DBMS_OUTPUT.PUT_LINE('EL USUARIO CONECTADO ES: '|| USER);
  
END;