 --CREACION DE DICHA TABLA  
  CREATE TABLE BITACORAS(
  PK_COD_BITACORA NUMBER PRIMARY KEY,
  DESCRIPCION VARCHAR2(2000),
  FECHA_HORA TIMESTAMP,
  USUARIO VARCHAR2(100),
  OPERACION VARCHAR2(50)
  );
  
  --CREANDO SECUENCIA
  CREATE SEQUENCE SQ_BITAGORAS
  START WITH 1
  INCREMENT BY 1;
  
  --CREANDO TRIGGER PARA LA TABLA CATEGORIAS
  CREATE OR REPLACE TRIGGER TG_CATEGORIAS
  AFTER INSERT ON CATEGORIES
  FOR EACH ROW
  DECLARE
  --CON ESTO AUTORIZAMOS EL USO DE UNA TRANSACCION AUTONOMA OSEA PODEMOS USAR COMMIT Y ROLLBACK ADENTRO DE UN TRIGGER
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    INSERT INTO BITACORAS VALUES (SQ_BITAGORAS.NEXTVAL,'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL NUEVO DATO EN EL ID ES: '||:NEW.CATEGORY_ID||' Y EL NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, 
    SYSTIMESTAMP, USER,'OPERACION INSERT');
    COMMIT;
    --AQUI HACEMOS ROLLBACK SI SE GENERA ALGUN ERROR ADENTOR DEL TRIGGER Y ASI DESACEMOS LO CAMBIOS.
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
  END;
----PROBANDO EL FUNCIONAMIENTO DEL TRIGGER
BEGIN
  INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BICICLETAS PLAYERAS' );
  COMMIT;
END;