--ESTRUCCUTURA BASICA DE LOS TRIGGERS
CREATE OR REPLACE TRIGGER TG_SQ_TABLA_CATEGORIAS
--DESIDIMOS SI QUEREMOS EJECUTAR ANTES O DESPUES DE LA OPERACION INSERT Y LUEGO DEFINIMOS EN QUE TABLA ESTA ACTIVO DICHO TG
BEFORE INSERT ON CATEGORIES
--AQUI LE DECIMOS QUE POR CADA LINEA INGRESADA SE EJECUTARA EL TG
FOR EACH ROW
DECLARE

BEGIN
  :NEW.CATEGORY_ID:=SQ_TABLA_CATEGORIAS.NEXTVAL;
END;

---------------------------------------------------------------------------------
--PRUEBA DE TRIGGER
DECLARE
begin
  INSERT INTO CATEGORIES (CATEGORY_NAME)VALUES ('BICICLETAS URBANAS');
  INSERT INTO CATEGORIES (CATEGORY_NAME)VALUES ('BICICLETAS MONTANIA');
  commit;
end;