--CREANDO TRIGGER PARA PODER GESTIONAR TANTO INSERT, UPDATE, DELETE CON UN SOLO TRIGGER
  CREATE OR REPLACE TRIGGER TG_CATEGORIAS
  --AQUI DONDE PONEMOS LAS 3 OPERACIONES
  AFTER INSERT OR UPDATE OR DELETE ON CATEGORIES
  FOR EACH ROW
  BEGIN
  --VERIFICANDO SI LA OPERACION ES UN INSERT
    IF (INSERTING) THEN
      INSERT INTO BITACORAS VALUES (SQ_BITAGORAS.NEXTVAL,'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL NUEVO DATO EN EL ID ES: '||:NEW.CATEGORY_ID||' Y EL NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, 
      SYSTIMESTAMP, USER,'OPERACION INSERT');
    END IF;
   --VERIFICANDO SI LA OPERACION ES UN UPDATE
    IF (UPDATING) THEN
      INSERT INTO BITACORAS VALUES (SQ_BITAGORAS.NEXTVAL,'SE REALIZO UN UPDATE EN LA TABLA CATEGORIAS Y EL NOMBRE ANTERIOR DE LA CATEGORIES ES: '||:OLD.CATEGORY_NAME||' Y EL NUEVO NOMBRE DE LA CATEGORIA ES: '||:NEW.CATEGORY_NAME, 
      SYSTIMESTAMP, USER,'OPERACION UPDATE');
    END IF;
   --VERIFICANDO SI LA OPERACION ES UN DELETE
    IF (DELETING)THEN
          INSERT INTO BITACORAS VALUES (SQ_BITAGORAS.NEXTVAL,'SE REALIZO UN DELETE EN LA TABLA CATEGORIAS Y EL NOMBRE ELIMINADO FUE: '||:OLD.CATEGORY_NAME, 
          SYSTIMESTAMP, USER,'OPERACION DELETE');
    END IF;
    
  END;
--PROBANDO TRIGGER PARA INSERT
  BEGIN
    INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BMX');
    COMMIT;
  END;
--PROBANDO TRIGGER PARA UPDATE
  BEGIN
    UPDATE CATEGORIES SET CATEGORY_NAME='BICIS PARA ASALTANTES' WHERE CATEGORY_ID=53;
    COMMIT;
  END;
--PROBANDO TRIGGER PARA DELETE
  BEGIN
    DELETE CATEGORIES WHERE CATEGORY_ID=52;
    COMMIT;
  END;