--USO DE COMMMIT Y DE ROLLBACK
DECLARE

BEGIN
--TENEMOS QUE APROBAR CADA TRANSACCION
  INSERT INTO BRANDS VALUES (13,'MOUNTAIN BICI');
  commit;
  INSERT INTO BRANDS VALUES (14,'BICI SHOP');
  commit;
  INSERT INTO BRANDS VALUES (12, 'ELECTRO BICI');
  --COMANDO PARA APROBAR QUE UN TRANSACCION 
  commit;
  
  EXCEPTION 
  --ESTA EXCEPTION LO QUE NOS DICE QUE HAY UNA VIOLACION DE ALGUNA LLAVE PRIMARIA.
  WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA, CODIGO DE ERROR: '||SQLCODE);
    ROLLBACK;
END;

SET SERVEROUTPUT ON;

---------------------------------------------------------------------------------
--USO DE LOS SAVEPOINT
DECLARE

BEGIN
  UPDATE BRANDS SET BRAND_NAME=BRAND_NAME||'2019' WHERE BRAND_ID=10 OR BRAND_ID=11;
  UPDATE BRANDS SET BRAND_NAME=BRAND_NAME||'2020' WHERE BRAND_ID=12 OR BRAND_ID=13;
  COMMIT;
  --PUNTO DE GUARDADO
  SAVEPOINT DATOS_MODIFICADOS;
  UPDATE BRANDS SET BRAND_ID=1, BRAND_NAME=BRAND_NAME||'2021' WHERE BRAND_ID=14;
  COMMIT;
  SAVEPOINT DATOS_MODIFICADOS;
  
  EXCEPTION 
  --ESTA EXCEPTION LO QUE NOS DICE QUE HAY UNA VIOLACION DE ALGUNA LLAVE PRIMARIA.
  WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA, CODIGO DE ERROR: '||SQLCODE);
    ROLLBACK TO SAVEPOINT DATOS_MODIFICADOS;
END;
